from core.variants import generate_variants


def test_generates_deduplicated_candidates():
    candidates = generate_variants("example", keywords=["mytest"], tlds=["com"])
    domains = [c.domain for c in candidates]

    assert len(domains) == len(set(domains)), "no duplicate domains"
    assert "example.com" not in domains, "original domain is excluded"


def test_dictionary_keywords_produce_combosquat_variants():
    candidates = generate_variants("example", keywords=["mytest"], tlds=["com"])
    dictionary_hits = {c.domain for c in candidates if c.fuzzer == "dictionary"}

    assert "example-mytest.com" in dictionary_hits
    assert "mytest-example.com" in dictionary_hits
    # built-in combosquat keywords are always merged in
    assert "example-login.com" in dictionary_hits


def test_tld_swap_uses_configured_tlds():
    candidates = generate_variants("example", tlds=["com", "net", "io"])
    tld_swaps = {c.domain for c in candidates if c.fuzzer == "tld-swap"}

    # Exact brand name under a TLD you don't run the seed for is a real,
    # valuable finding (e.g. someone squats yourbrand.net when you only
    # run yourbrand.com) — it surfaces here via the other seeds' tld-swap
    # pass, since only the *exact* (name, seed-tld) pair is excluded.
    assert "example.net" in tld_swaps
    assert "example.io" in tld_swaps
    assert "example.com" in tld_swaps


def test_default_tlds_used_when_none_given():
    candidates = generate_variants("example")
    assert len(candidates) > 0


def test_idn_homograph_candidates_are_generated():
    """Full-script Unicode homograph attacks (e.g. Cyrillic characters
    that render visually identical to Latin ones) are generated by
    dnstwist's dedicated 'cyrillic' fuzzer category automatically — no
    extra flag or code needed. Output is valid Punycode (xn--...), the
    correct ASCII-compatible encoding for real DNS/RDAP queries, and
    decodes back to a domain that's visually indistinguishable from the
    brand name. Verified against a real IDN homograph attack pattern for
    "apple" (аррӏе — Cyrillic а/р/р, Palochka ӏ in place of Latin l)."""
    candidates = generate_variants("apple", tlds=["com"])
    cyrillic_hits = [c for c in candidates if c.fuzzer == "cyrillic"]

    assert len(cyrillic_hits) >= 1
    domain = cyrillic_hits[0].domain
    assert domain.startswith("xn--"), "must be valid Punycode, not raw Unicode"

    label = domain.split(".")[0]
    decoded = label.encode("ascii").decode("idna")
    assert decoded != "apple", "must actually differ from the real brand name"
    assert any(ord(ch) > 127 for ch in decoded), "must contain non-ASCII confusable characters"


def test_homoglyph_fuzzer_also_produces_valid_punycode():
    """Not just the dedicated 'cyrillic' category — the broader
    'homoglyph' fuzzer (individual look-alike character substitutions)
    also emits non-ASCII results as valid Punycode automatically."""
    candidates = generate_variants("apple", tlds=["com"])
    homoglyphs = [c for c in candidates if c.fuzzer == "homoglyph"]
    punycode_homoglyphs = [c for c in homoglyphs if c.domain.startswith("xn--")]

    assert len(punycode_homoglyphs) > 0
    # every one must round-trip through IDNA decoding without error
    for c in punycode_homoglyphs[:20]:
        label = c.domain.split(".")[0]
        label.encode("ascii").decode("idna")  # raises if invalid
